/**
 * Reusable utility to upload large video files directly to Cloudflare R2 via presigned PUT URLs with progress tracking.
 * 
 * @param {object} params
 * @param {string} params.uploadUrl - Presigned PUT URL generated by the backend
 * @param {File} params.file - Video binary file from file input
 * @param {function(number): void} [params.onProgress] - Progress callback receiving percentage (0-100)
 * @returns {Promise<boolean>} Resolves to true when upload completes successfully
 */
export function uploadToR2WithProgress({ uploadUrl, file, onProgress }) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("PUT", uploadUrl, true);
    xhr.setRequestHeader("Content-Type", file.type || "video/mp4");

    if (xhr.upload && onProgress) {
      xhr.upload.onprogress = (event) => {
        if (event.lengthComputable) {
          const percentComplete = Math.round((event.loaded / event.total) * 100);
          onProgress(percentComplete);
        }
      };
    }

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        if (onProgress) onProgress(100);
        resolve(true);
      } else {
        reject(new Error(`Direct R2 upload failed with HTTP status ${xhr.status}.`));
      }
    };

    xhr.onerror = () => {
      reject(new Error("Network error occurred during direct R2 video upload."));
    };

    xhr.onabort = () => {
      reject(new Error("Video upload was aborted."));
    };

    xhr.send(file);
  });
}
